BeachEquipmentStore.Web/Controllers/CategoryController.cs
namespace BeachEquipmentStore.Web.Controllers
{
    using BeachEquipmentStore.Services.Interfaces;
    using BeachEquipmentStore.ViewModels.Category;
    using Microsoft.AspNetCore.Mvc;

    public class CategoryController : Controller
    {
        private readonly ICategoryService _categories;

        public CategoryController(ICategoryService categories)
        {
            _categories = categories;
        }

        [Route("Categories")]
        public async Task<IActionResult> AllCategories()
        {
            var allCategories = await _categories.GetAllCategoriesAsync();

            List<CategoryViewModel> resultCategories = allCategories
                .Select(c => new CategoryViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    ImageUrl = c.ImageUrl
                })
                .ToList();

            return View(resultCategories);
        }
    }
}

BeachEquipmentStore.Web/Controllers/ManufacturerController.cs
namespace BeachEquipmentStore.Web.Controllers
{
    using BeachEquipmentStore.Services.Interfaces;
    using BeachEquipmentStore.ViewModels.Manufacturer;
    using Microsoft.AspNetCore.Mvc;

    public class ManufacturerController : Controller
    {
        private readonly IManufacturerService _manufacturers;

        public ManufacturerController(IManufacturerService manufacturers)
        {
            this._manufacturers = manufacturers;
        }

        [Route("Manufacturers")]
        public async Task<IActionResult> AllManufacturers()
        {
            var allManufacturers = await _manufacturers.GetAllManufacturersAsync();

            List<ManufacturerViewModel> resultManufacturers = allManufacturers
                .Select(m => new ManufacturerViewModel
                {
                    Id = m.Id,
                    Name = m.Name,
                    ImageUrl = m.ImageUrl
                })
                .ToList();

            return View(resultManufacturers);
        }
    }
}

BeachEquipmentStore.Web/Views/Shared/_AddToCartPartial.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity

<form method="post" asp-controller="Cart" asp-action="Add" asp-route-productId="@Model.Id">
    <div class="container">
        <div class="row align-items-end">
            <div class="col">
                <input type="number" class="form-control" name="quantity" value="1" required>
            </div>
            <div class="col">
                <button class="btn btn-primary btn-block" type="submit">Добави в количката</button>
            </div>
        </div>
    </div>
    @Html.AntiForgeryToken()
</form>

BeachEquipmentStore.Web/Views/Shared/_FilterProducts.cshtml
<div>
    <form id="filter-form" method="get" asp-controller="Product">
        <div style="justify-content">
            <span class="">
                <label for="keyword">Ключова дума:</label>
                <input type="text" id="keyword" name="keyword" value="@Model.Keyword" />
            </span>
            <span>
                <label for="category-dropdown">Категория:</label>
                <select id="category-dropdown" name="categoryId" value="@Model.CategoryId">
                    <option value="">Всички категории</option>
                    @foreach (var category in Model.FilteredProducts.Categories)
                    {
                        <option value="@category.Id" selected="@(Model.CategoryId == category.Id)">@category.Name</option>
                    }
                </select>
            </span>
            <span>
                <label for="manufacturer-dropdown">Марка:</label>
                <select id="manufacturer-dropdown" name="manufacturerId" value="@Model.ManufacturerId">
                    <option value="">Всички марки</option>
                    @foreach (var manufacturer in Model.FilteredProducts.Manufacturers)
                    {
                        <option value="@manufacturer.Id" selected="@(Model.ManufacturerId == manufacturer.Id)">@manufacturer.Name</option>
                    }
                </select>
            </span>
            <span>
                <button type="button" id="clear-filters-button" style="color:white; background-color:#f50a10">Премахни филтрите</button>
                <button type="submit" style="color:white; background-color:#2317c3"
                        asp-action="All" asp-route-keyword="@(Model.Keyword ?? "")" asp-route-categoryId="@(Model.CategoryId ?? "")" asp-route-manufacturerId="@(Model.ManufacturerId ?? "")">
                    Приложи филтрите
                </button>
            </span>
        </div>
        @Html.AntiForgeryToken()
    </form>
</div>

<script src="~/js/filter_products.js" asp-append-version="true"></script>

BeachEquipmentStore.Web/Views/Shared/_GetProductsPartial.cshtml
<div class="container mt-5">
    <div class="row">
        @if (Model.FilteredProducts.Products.Count > 0)
        {
            @foreach (var product in Model.FilteredProducts.Products)
            {
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <a asp-controller="Product" asp-action="GetSelectedProduct" asp-route-productId="@product.Id">
                                <img src="@Url.Content(product.ImageUrl)" class="card-img-top product-image" alt="@product.Name">
                                <div class="card-body product-card-body">
                                    <h5 class="card-title">@product.Name</h5>
                                    <p class="card-text">@product.Price.ToString("C")</p>
                                </div>
                            </a>
                            <partial name="_AddToCartPartial" model="@product" class="card-button" />
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h2>Няма намерени продукти, които да съвпадат със зададените критерии!</h2>
        }
    </div>
</div>

BeachEquipmentStore.Web/Views/Shared/_Layout.cshtml
@inject IUserService UserService

@{
    var user = await UserService.GetCurrentUserAsync(User);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BeachEquipmentStore.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="container landing-page bg-white" style="margin-top:10px; margin-bottom:20px;">
            <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-2 mt-2">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ицо Бийч</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="All">Каталог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="AllCategories">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manufacturer" asp-action="AllManufacturers">Марки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">За нас</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Контакти</a>
                        </li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial", user)
                </div>
            </nav>
        </div>
    </header>
    <div class="content-container">
        <main role="main" class="pb-0 mb-0">
            <div class="container landing-page bg-white pb-2 mb-2">

                @if (TempData.ContainsKey("Message"))
                {
                    <div class="alert alert-success" style="margin-top: 30px;">
                        @TempData["Message"]
                    </div>
                }

                @if (TempData.ContainsKey("ErrorMessage"))
                {
                    <div class="alert alert-danger" style="margin-top: 30px;">
                        @TempData["ErrorMessage"]
                    </div>
                }

                @RenderBody()
                @RenderSection("DynamicContent", required: false)

            </div>
            <div id="preloader" style="display: flex; justify-content: center; align-items: center;">
                <div class="lds-spinner">
                    <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
                </div>
            </div>
        </main>
    </div>

    <footer class="text-center text-white" style="background-color: #3f51b5">
        <!-- Grid container -->
        <div class="container">
            <!-- Section: Links -->
            <section class="mt-5">
                <!-- Grid row-->
                <div class="row text-center d-flex justify-content-center pt-5">
                    <!-- Grid column -->
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a asp-controller="Home" asp-action="About" class="text-white">За Нас</a>
                        </h6>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a asp-controller="Product" asp-action="All" class="text-white">Каталог</a>
                        </h6>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a href="#!" class="text-white">Awards</a>
                        </h6>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a href="#!" class="text-white">Help</a>
                        </h6>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2">
                        <h6 class="text-uppercase font-weight-bold">
                            <a asp-controller="Home" asp-action="Contact" class="text-white">Контакт</a>
                        </h6>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row-->
            </section>
            <!-- Section: Links -->

            <hr class="my-5" />

            <!-- Section: Text -->
            <section class="mb-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-8">
                        <p>
                            Ицо Бийч е професионална платформа за онлйан търговия. Ние Ви предоставяме широка гама от най-качествените продукти за плаж от множество установили се на пазара производители. Ние сме фокусирани върху осигуряване на възможно най-приятното прекарване на морскоро крайбрежие както за малчуганите, така и за техните родители. Стараем се да сме надеждни и да знаете, че може да разчитате на нас. Искрено се надяваме да останете толкова удовлетворени от нашите услуги, колкото ние сме удовлетворени да Ви ги предоставяме!
                        </p>
                    </div>
                </div>
            </section>
            <!-- Section: Text -->
            <!-- Section: Social -->
            <section class="text-center mb-5">
                <a href="https://www.facebook.com/" class="text-white me-4">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="https://x.com/" class="text-white me-4">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="https://www.google.com/" class="text-white me-4">
                    <i class="fab fa-google"></i>
                </a>
                <a href="https://www.instagram.com/" class="text-white me-4">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="https://www.linkedin.com/" class="text-white me-4">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="https://github.com/" class="text-white me-4">
                    <i class="fab fa-github"></i>
                </a>
            </section>
            <!-- Section: Social -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3"
             style="background-color: rgba(0, 0, 0, 0.2)">
            © @DateTime.Now.Year Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">Ицо Бийч ЕООД</a>
        </div>
        <!-- Copyright -->
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BeachEquipmentStore.Web/Views/Shared/_ManageNav.cshtml
<nav class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
    <div class="sidebar-sticky" style="width: 200px;">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" asp-controller="Profile" asp-action="MyProfile">Моят профил</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Profile" asp-action="EditProfile">Редакция на профила</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Profile" asp-action="ChangePassword">Промяна на парола</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Profile" asp-action="GetAddresses">Редакция на адреса</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Profile" asp-action="OrderHistory">История на поръчките</a>
            </li>
        </ul>
    </div>
</nav>